const dotenv = require('dotenv')
dotenv.config({ path: `${process.cwd()}/.env` })

const FIRST_APP_PORT = process.env.FIRST_APP_PORT
const FIRST_APP_HOST = process.env.FIRST_APP_HOST
const FIRST_APP_PATH = process.env.FIRST_APP_PATH
const FIRST_TEST_BASE_DATABASE_NAME = process.env.FIRST_TEST_BASE_DATABASE_NAME
const FIRST_TEST_BASE_DATABASE_HOST = process.env.FIRST_TEST_BASE_DATABASE_HOST
const FIRST_TEST_BASE_DATABASE_PORT = process.env.FIRST_TEST_BASE_DATABASE_PORT
const FIRST_TEST_BASE_DATABASE_USERNAME = process.env.FIRST_TEST_BASE_DATABASE_USERNAME
const FIRST_TEST_BASE_DATABASE_PASSWORD = process.env.FIRST_TEST_BASE_DATABASE_PASSWORD
const FIRST_TEST_BASE_DATABASE_AUTO_CREATE = process.env.FIRST_TEST_BASE_DATABASE_AUTO_CREATE

module.exports = {
	FIRST_APP_PORT,
	FIRST_APP_HOST,
	FIRST_APP_PATH,
	FIRST_TEST_BASE_DATABASE_NAME,
	FIRST_TEST_BASE_DATABASE_HOST,
	FIRST_TEST_BASE_DATABASE_PORT,
	FIRST_TEST_BASE_DATABASE_USERNAME,
	FIRST_TEST_BASE_DATABASE_PASSWORD,
	FIRST_TEST_BASE_DATABASE_AUTO_CREATE
}